import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { NavigationMenuDemo } from "@/components/navigation-menu";
import { ModeToggle } from "@/components/mode-toggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className="fixed z-50 w-full top-0 left-0">
            <div className="w-full h-2 bg-linear-to-r from-purple-400 via-pink-500 to-red-500 animate-gradient-x"></div>
            <div className="flex justify-center h-full w-full pt-4 bg-background">
              <NavigationMenuDemo />
              <ModeToggle />
            </div>
          </div>
          <div className="w-full min-h-screen relative top-20">
            {children}
          </div>
          <div className="h-16" />
        </ThemeProvider>

      </body>
    </html >
  );
}
