import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { NavigationMenuDemo } from "@/components/navigation-menu";
import { ModeToggle } from "@/components/mode-toggle";
import Providers from "./providers";

const barlow = Barlow({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-barlow",
});

export const metadata: Metadata = {
  title: "My Next.js App",
  description: "Generated by Peiwen Tang",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={barlow.className}>
      <body
        className={`antialiased`}
      >
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <div className="fixed z-50 w-full top-0 left-0">
              <div className="w-full h-2 bg-linear-to-r from-purple-400 via-pink-500 to-red-500 animate-gradient-x"></div>
              <div className="flex justify-center h-full w-full pt-4 bg-background">
                <NavigationMenuDemo />
                <ModeToggle />
              </div>
            </div>
            <div className="w-full min-h-screen relative top-20">
              {children}
            </div>
            <div className="h-16" />
          </ThemeProvider>
        </Providers>
      </body>
    </html >
  );
}
